repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.0
    hooks:
      - id: clang-format
        types_or: [text]
        files: \.glsl$
